FROM abyssos/abyss
RUN apk add --no-cache bash bsdtar git gmake llvm patch
RUN [ "/usr/bin/ln", "-s", "/usr/bin/gmake", "/usr/bin/make" ]
RUN [ "/usr/bin/ln", "-s", "/usr/bin/bsdtar", "/usr/bin/tar" ]
